fix: AttributeError: 'ClinicalProcedure' object has no attribute 'radiology_examination_template'
(cherry picked from commit 09c404b25b47603cdf1215ba27e9e652504429e8)